name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the version of Node.js required for your project

    - name: Install Dependencies
      run: npm install

    - name: Run SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Your SonarQube token stored as a secret
      run: |
        npx sonarqube-scanner \
          -Dsonar.projectKey=sq-test \
          -Dsonar.organization=beatrs \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io
